name: Update API

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Enter venv
      run: python3 -m venv backend
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Restart service
      run: sudo systemctl restart arg-backend

